# Generated by Django 2.0 on 2018-12-01 01:34

import django.contrib.auth.password_validation
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='权限名称')),
                ('allow_url', models.CharField(max_length=256, verbose_name='权限url')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='角色名称')),
                ('permissons', models.ManyToManyField(blank=True, to='snow.Permission', verbose_name='权限')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名称')),
                ('password', models.CharField(max_length=16, validators=[django.contrib.auth.password_validation.CommonPasswordValidator], verbose_name='密码')),
                ('email', models.CharField(max_length=64, validators=[django.core.validators.EmailValidator], verbose_name='邮箱')),
                ('roles', models.ManyToManyField(to='snow.Role', verbose_name='角色')),
            ],
        ),
    ]
