# Generated by Django 2.0 on 2018-12-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_meun',
            field=models.BooleanField(default=0, verbose_name='是否成为菜单'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=16, verbose_name='密码'),
        ),
    ]
