# Generated by Django 2.0 on 2018-12-01 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0002_auto_20181201_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='一级菜单名称')),
                ('icon', models.CharField(blank=True, max_length=64, null=True, verbose_name='标签')),
            ],
        ),
        migrations.RemoveField(
            model_name='permission',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='is_meun',
        ),
        migrations.AddField(
            model_name='permission',
            name='meun',
            field=models.ForeignKey(blank=True, help_text='null不可作为菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='snow.Menu', verbose_name='子菜单'),
        ),
    ]
