# Generated by Django 2.0 on 2018-12-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0004_permission_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='url_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='url别名'),
        ),
    ]
