# Generated by Django 2.0 on 2018-12-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0005_permission_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(max_length=64, verbose_name='标签'),
        ),
    ]
