# Generated by Django 2.0 on 2018-12-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0006_auto_20181201_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='meun',
            field=models.ForeignKey(blank=True, help_text='null不可作为菜单,说白了就是只能在body里面展示，能不能出现在菜单栏', null=True, on_delete=django.db.models.deletion.CASCADE, to='snow.Menu', verbose_name='子菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='与哪一个菜单栏关联', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='snow.Permission', verbose_name='关联父菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(max_length=16, unique=True, verbose_name='权限名称'),
        ),
    ]
